# Generated by Django 4.2.16 on 2024-10-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('datetime', models.DateTimeField(verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('task', models.TextField(max_length=10000, verbose_name='Описание')),
            ],
        ),
    ]
